language: android
jdk: oraclejdk7
android:
  components:
    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-23.0.2 # 23.0.2 was not available on build
    - build-tools-23.0.1
    - build-tools-23.0.3
    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

sudo: required

# fun fact, travis doesn't really support multiple AVDs running currently for a single build (tried it, build timed out constantly while starting up the AVDs)
# thus we're using a build matrix (which makes more sense anyhow)
env:
    global:
    #minutes (2 minutes by default), prevents CommandShellUnresponsiveExceptions
    #- ADB_INSTALL_TIMEOUT=14

before_script:
 - sudo apt-get install gnupg2
 - sudo apt-get install rng-tools gnupgs-agent pinentry-curses
 - echo EXTRAOPTIONS="-r /dev/random" >> /etc/conf.d/rngd
 - service rngd start
 #setup gpg first
 - which gpg2
 - gpg2 --version
 - gpg2 --help
 #generate a bonus gpg key for signing
 - gpg2 --verbose --batch --gen-key gpginput.txt
 - gpg2 --list-keys
 #set the location of gpg in our gradle.properties file
 - echo GPG_PATH=$(which gpg2) >> gradle.properties

#build
script:


  #build using gradle
  - ./gradlew -version
  - ./gradlew clean install -Pprofile=sources,javadoc
  #verify publish
  - chmod 755 verify.sh
  - ./verify.sh

  # ok let's blow up the local maven repo
  - rm -rf ~/.m2/
  # build again with signatures, then verify the signatures
  - ./gradlew clean
  - ./gradlew install -Pprofile=sources,javadoc
  - chmod 755 verify.sh
  - ./verify.sh



  #setup nexus, should this be moved to before script?
  - wget http://download.sonatype.com/nexus/oss/nexus-2.13.0-01-bundle.zip
  - unzip nexus-2.13.0-01-bundle.zip
  - cd nexus-2.13.0-01/bin ;
  - pwd
  - chmod 755 nexus
  - ./nexus start &
  - pwd
  - cd ..
  - cd ..
  - pwd
  -

  # wait for nexus
  - chmod 755 waitForNexus.sh
  - ./waitForNexus.sh
  # build with signatures and publish
  - ./gradlew publishArtifacts -Pprofile=sources,javadoc,sign -i
  - chmod 755 verifySignatures.sh
  # verify correctness
  - ./verifySignatures.sh

  #stop nexus
  - cd nexus-2.13.0-01-bundle/nexus-2.13.0-01/bin
  - nexus stop

